### ISSUE TITLE
openwrt 5.4.117 ERROR

### ISSUE THREAD

**Issue by vpei** [Greg798100/rtl8189es#1]
Applying ./patches/011-activate-all-backport-code.patch using plaintext: 
patching file include/drv_types.h
Hunk #1 FAILED at 105.
1 out of 1 hunk FAILED -- saving rejects to file include/drv_types.h.rej
The next patch would create the file include/rtl_sta_info.h,
which already exists!  Applying it anyway.
patching file include/rtl_sta_info.h
Hunk #1 FAILED at 1.
1 out of 1 hunk FAILED -- saving rejects to file include/rtl_sta_info.h.rej
The next patch would delete the file include/sta_info.h,
which does not exist!  Applying it anyway.
patching file include/sta_info.h
Hunk #1 FAILED at 1.
1 out of 1 hunk FAILED -- saving rejects to file include/sta_info.h.rej
patching file os_dep/linux/ioctl_cfg80211.c
Hunk #1 FAILED at 798 (different line endings).
Hunk #2 FAILED at 807 (different line endings).
Hunk #3 FAILED at 1890 (different line endings).
Hunk #4 FAILED at 2043 (different line endings).
Hunk #5 FAILED at 4008 (different line endings).
Hunk #6 FAILED at 6411 (different line endings).
6 out of 6 hunks FAILED -- saving rejects to file os_dep/linux/ioctl_cfg80211.c.rej
Patch failed!  Please fix ./patches/011-activate-all-backport-code.patch!

ERROR: package/kernel/rtl8189es failed to build.

**Comment by Greg798100** [comment]
Hi, not build on new kernel
